### ISSUE TITLE
Install Issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by gideonsimpson** [libAtoms/JuLIP.jl#75] opened 2017-12-01 18:50 UTC
When trying to install, I got the following error:
```
Successfully installed pip-9.0.1 setuptools-38.2.3 wheel-0.30.0
================================[ ERROR: JuLIP ]================================

LoadError: could not spawn `/usr/bin/pip install --upgrade --user ase`: no such file or directory (ENOENT)
while loading /home/grs53drexel/.julia/v0.6/JuLIP/deps/build.jl, in expression starting on line 35

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: JuLIP had build errors.

 - packages with build errors remain installed in /home/grs53drexel/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("JuLIP")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```

**Comment by cortner** [comment] 2017-12-01 18:59
I can reproduce this. simply go to a terminal, and type 
```
pip install --upgrade --user ase
```
Let me know if this works.

**Comment by cortner** [comment] 2017-12-01 19:04
I think the problem here is that `pip` was used right after it was installed. Why this shouldn't work I have no idea.

**Comment by cortner** [comment] 2017-12-01 19:09
If this solution works on your system then I'll add something to the README

**Comment by gideonsimpson** [comment] 2017-12-01 22:11
I tried that, then I got this:
```
julia> Pkg.build("JuLIP")
INFO: Building SpecialFunctions
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.12) at /usr/bin/python, libpython = libpython2.7
INFO: /home/grs53drexel/.julia/v0.6/PyCall/deps/deps.jl has been updated
INFO: /home/grs53drexel/.julia/v0.6/PyCall/deps/PYTHON has not changed
INFO: Building Dierckx
make: Nothing to be done for 'all'.
INFO: Building JuLIP
Installing Dependencies of `JuLIP.jl`: `ase` and `matscipy`
`matscipy` was not found, trying to install it. If this fails,
please file an issue and try to install it manually, following
the instructions at `https://github.com/libAtoms/matscipy`
I couldn't find `pip`. I will try to download and install it
automatically, but if this fails, please install
manually, then try to build `JuLIP` again.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1558k  100 1558k    0     0  4098k      0 --:--:-- --:--:-- --:--:-- 4100k
Requirement already up-to-date: pip in /home/grs53drexel/.local/lib/python2.7/site-packages
===========================================================================[ ERROR: JuLIP ]============================================================================

LoadError: could not spawn `/usr/bin/pip install --upgrade --user matscipy`: no such file or directory (ENOENT)
while loading /home/grs53drexel/.julia/v0.6/JuLIP/deps/build.jl, in expression starting on line 44

=======================================================================================================================================================================

===========================================================================[ BUILD ERRORS ]============================================================================

WARNING: JuLIP had build errors.

 - packages with build errors remain installed in /home/grs53drexel/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("JuLIP")`
 - build a single package by running its `deps/build.jl` script

=======================================================================================================================================================================
```,
so I then performed ``pip install --upgrade --user matscipy``, followed by a ``Pkg.build("JuLIP")``.  Now, I get the error:
```
julia> using JuLIP
ERROR: LoadError: LoadError: UndefVarError: JuLIP not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] _require(::Symbol) at ./loading.jl:490
 [6] require(::Symbol) at ./loading.jl:405
while loading /home/grs53drexel/.julia/v0.6/JuLIP/src/preconditioners.jl, in expression starting on line 14
while loading /home/grs53drexel/.julia/v0.6/JuLIP/src/JuLIP.jl, in expression starting on line 56
```

**Comment by cortner** [comment] 2017-12-01 22:32
try `Pkg.checkout("JuLIP")` and then try again?

sorry this is probably frustrating. mainly because I haven't stress tested the installation on anybody yet :)

**Comment by cortner** [comment] 2017-12-01 22:34
I now think what is causing this is conflicts between the Python used by Julia and the system Python.

**Comment by cortner** [comment] 2017-12-01 22:43
Here is how to choose the python version: (copied from PyCall.jl README)

Specifying the Python version

If you want to use a different version of Python than the default, you can change the Python version by setting the PYTHON environment variable to the path of the python executable and then re-running Pkg.build("PyCall"). In Julia:

ENV["PYTHON"] = "... path of the python program you want ..."
Pkg.build("PyCall")
Note also that you will need to re-run Pkg.build("PyCall") if your python program changes significantly (e.g. you switch to a new Python distro, or you switch from Python 2 to Python 3).

To force Julia to use its own Python distribution, via Conda, simply set ENV["PYTHON"] to the empty string "" and re-run Pkg.build("PyCall").

**Comment by gideonsimpson** [comment] 2017-12-02 18:12
Did the checkout, rebuilt PyCall (using the system Python 2.7), and rebuilt JuLIP.  Now I get:
```
julia> using JuLIP
WARNING: failed to load `PyAMG`
ERROR: LoadError: LoadError: UndefVarError: RugeStubenSolver not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] _require(::Symbol) at ./loading.jl:490
 [6] require(::Symbol) at ./loading.jl:405
while loading /home/grs53drexel/.julia/v0.6/JuLIP/src/preconditioners.jl, in expression starting on line 521
while loading /home/grs53drexel/.julia/v0.6/JuLIP/src/JuLIP.jl, in expression starting on line 56
```

**Comment by cortner** [comment] 2017-12-02 18:40
PyAMG should have installed itself automatically. Not sure what happened. I’ll send instructions when I’m on a keyboard

**Comment by cortner** [comment] 2017-12-02 18:52
From terminal: pip install pyamg

From Julia real: Pkg.add("PyAMG")

Then try again?

**Comment by gideonsimpson** [comment] 2017-12-02 19:01
Ok, now it's loading.  I'll just add that this was on a vanilla Ubuntu 16.04 system and I was using the system Python 2.7.12.

**Comment by cortner** [comment] 2017-12-02 19:07
Thank you. I guess I’ll have to go back and gonover installation again.

**Comment by cortner** [comment] 2018-03-08 09:39
moving this to ASE.jl

**Closed by cortner** 2018-03-08 09:39 UTC
