### ISSUE TITLE
Inconsistency with LAMMPS

### ISSUE THREAD

**Issue by gideonsimpson** [libAtoms/JuLIP.jl#76] opened 2017-12-02 22:19 UTC
I'm comparing some stuff to some existing lammps code of mine, and I'm noticing some inconsistencies.  This may have more to do with ASE, but it's troubling.  The test problem is to quench a LJ7 cluster in 2D to its ground state given initial positions on a unit disc.  Here is the lammps code:

```
boundary p p p
units lj
atom_style atomic
atom_modify map array sort 0 0.0
dimension 2
region box block 0 5 0 5 -.5 .5 units box
create_box 1 box
create_atoms 1 single 2.5 2.5 0
create_atoms 1 single 3.5 2.5 0
create_atoms 1 single 3.0 3.366025403784439 0
create_atoms 1 single 2.0 3.366025403784439 0
create_atoms 1 single 1.5 2.5 0
create_atoms 1 single 2.0 1.633974596215561 0
create_atoms 1 single 3.0 1.633974596215561 0

mass 1 1.0
pair_style lj/cut 2.5
pair_coeff 1 1 1.0 1.0
pair_modify shift yes
neighbor 0.3 bin
neigh_modify delay 0 every 1 check yes
run 0
write_dump all atom lj72d_init.out modify scale no

min_style cg
minimize 1.e-14 1.e-14 1000 1000
write_dump all atom lj72d_fin.out modify scale no
```
and the output shows that it gets:
```
ITEM: ATOMS id type x y z
1 1 2.5 2.5 0
2 1 3.61846 2.5 0
3 1 3.05923 3.46861 0
4 1 1.94077 3.46861 0
5 1 1.38154 2.5 0
6 1 1.94077 1.53139 0
7 1 3.05923 1.53139 0
```

In contrast, the lammps, I tried;
```
using JuLIP, JuLIP.ASE, JuLIP.Potentials
using ProgressMeter

# set up a heptamer
r0 = 1.0
N = 6
phi = linspace(0., (N-1)* 2*pi/N, N)|>collect
x0 = 2.5 # position of center
y0 = 2.5
x = x0 + [0; r0 * cos.(phi)]
y = y0 + [0; r0 * sin.(phi)]
X = [x';y';  zeros(N+1)']|> vecs
at = Atoms("H$(length(X))", X)
set_cell!(at, diagm([5, 5, 1.0]))
set_pbc!(at, (true, true, true))
set_constraint!(at, FixedCell2D(at))

lj = LennardJones(r0=2.^(1./6.), e0=1.) * HS(2.5)
set_calculator!(at, lj);
minimise!(at, precond=:id, gtol=1e-14)

q = position_dofs(at)
println(q)
```
and got 
```
[2.5, 2.5, 3.59109, 2.5, 3.04555, 3.44491, 1.95445, 3.44491, 1.40891, 2.5, 1.95445, 1.55509, 3.04555, 1.55509]
```
and while the difference is < 1%, it is still there, and it's not at all clear to me why it should be.

Note that lammps defines it's LJ potentials in a slightly different way, using epsilon and sigma units, but I believe  have compensated by that by including the factor of 2^(1/6) in r0 for Julia.

**Comment by cortner** [comment] 2017-12-02 22:58
can you explain exactly how this potential is defined: 
```
pair_style lj/cut 2.5
pair_coeff 1 1 1.0 1.0
pair_modify shift yes
```

**Comment by cortner** [comment] 2017-12-02 23:20
I would say to double check this result, I would implement the problem without either JuLIP or Lammps and check what the result will be

**Comment by gideonsimpson** [comment] 2017-12-03 00:31
``
pair_style lj/cut 2.5
``
sets the pair potential to be Lennard-Jones with a cutoff at 2.5 units (http://lammps.sandia.gov/doc/pair_lj.html)

``
pair_coeff 1 1 1.0 1.0
``
sets the interactions between atoms of type 1 with type 1 to be epsilon = 1.0 and sigma = 1.0 (http://lammps.sandia.gov/doc/pair_coeff.html)

``
pair_modify shift yes
``
shifts the potential so it is zero at the cutoff distance (http://lammps.sandia.gov/doc/pair_modify.html)

**Comment by gabor1** [comment] 2017-12-03 00:42
In quip we use force-shift so that the first derivative is also continuous. What do julip and lammps do?

-- Gábor

**Comment by gideonsimpson** [comment] 2017-12-03 02:27
After asking on the lammps list serve, the lj/cut potential does NOT have a continuous force.

**Comment by cortner** [comment] 2017-12-03 07:20
JuLIP does whatever you ask it to.

**Comment by cortner** [comment] 2017-12-03 07:21
I’ve implemented SW blending, spline blending, Shift, force shift, and curvature shift

**Comment by cortner** [comment] 2017-12-03 07:37
so my only explanation is that one of the neighbour lists is incorrect. Probably Lammps :).

**Comment by cortner** [comment] 2017-12-03 11:30
does lammps use minimal image convention?

**Comment by gabor1** [comment] 2017-12-03 11:38
yes

-- Gábor

**Comment by cortner** [comment] 2017-12-03 11:58
then most likely this is the reason, we can test this by decreasing the cut-off to 2.2

**Comment by gideonsimpson** [comment] 2017-12-03 16:56
That script is for vanilla lammps.  After installation, with whatever the installed lammps binary is, run:
```
:>lmp_bin < script.lammps
```

where script.lammps contains the above code.

**Comment by gideonsimpson** [comment] 2017-12-03 16:57
What’s the “minimal image convention” thing you’re referring to?

**Comment by gabor1** [comment] 2017-12-03 17:05
Many codes (for efficiency reasons) assume that only one periodic images of two particles are within the cutoff of the interaction. So they do not sum over multiple images, just find the shortest distance between all images and evaluate the interaction for that. This works when the system size is significantly bigger than the cutoff (precise condition depends on the cell angles), and gives bollocks (including discontinuities) when it is not. 

-- Gábor

**Comment by cortner** [comment] 2017-12-03 22:14
TEST 1: I've made the cells big enough that there is no interaction across cells at all.
```
3×7 Array{Float64,2}:
 0.0   1.11846      0.55923   -0.55923   -1.11846      -0.55923    0.55923
 0.0  -2.39808e-14  0.968615   0.968615  -2.30926e-14  -0.968615  -0.968615
 0.0   0.0          0.0        0.0        0.0           0.0        0.0
LAMMPS:
3×7 Array{Float64,2}:
 0.0  1.11846  0.55923  -0.55923  -1.11846  -0.55923   0.55923
 0.0  0.0      0.96861   0.96861   0.0      -0.96861  -0.96861
 0.0  0.0      0.0       0.0       0.0       0.0       0.0    Fuji:scratch ortner$
```

**Comment by cortner** [comment] 2017-12-03 23:45
This LAMMPS thing seems to have some problems. Here is a simpler test with just two atoms. I've made the cut-off small enough so that minimal image doesn't matter. 
```
boundary p p p
units lj
atom_style atomic
atom_modify map array sort 0 0.0
dimension 2
region box block 0 5 0 5 0 1 units box
create_box 1 box
create_atoms 1 single 0.0 0.0 0
create_atoms 1 single 1.0 0.0 0

mass 1 1.0
pair_style lj/cut 1.5
pair_coeff 1 1 1.0 1.0
pair_modify shift yes
neighbor 0.3 bin
neigh_modify delay 0 every 1 check yes
run 0
write_dump all atom lj72d_init.out modify scale no

min_style cg
minimize 1.e-14 1.e-14 1000 1000
write_dump all atom lj72d_fin.out modify scale no
```

The result (also with JuLIP) is 
```
# JuLIP: r = 1.0974260294435827
# LAMMPS: r = 1.1224600000000002
```

**Comment by cortner** [comment] 2017-12-03 23:46
Here is the problem: 1.1224600000000002 = 2^(1/6), which is the equilibrium distance of LJ but not the equilibrium distance between two infinite lines of LJ atoms , so the LAMMPS result cannot correct.

**Comment by cortner** [comment] 2017-12-03 23:47
we can talk more tomorrow - I'm already 1h late for bed :)

**Comment by gabor1** [comment] 2017-12-04 00:32
why is this not a minimum image issue along the line of particles?  

-- Gábor

**Comment by gideonsimpson** [comment] 2017-12-04 01:26
@cortner is the JuLIP formulation of periodicity the desired one?  Many view LAMMPS as the gold standard for this stuff.

**Comment by gabor1** [comment] 2017-12-04 08:03
Huh? Near my parts, lammps has quirks ppl put up with due to the speed and the ubuiquity.

-- Gábor

**Comment by gideonsimpson** [comment] 2017-12-04 16:13
Ok, following up on this, I tried making my computational domain larger (0,20) x (0,20), and putting the cluster in the center of that, at (10,10).  With an interaction range is only 2.5, the periodic images should be decoupled, no?  I'm still getting the same inconsistency.

**Comment by cortner** [comment] 2017-12-04 16:36
It is the z direction

Sent from my iPhone

On 4 Dec 2017, at 16:13, gideonsimpson <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, following up on this, I tried making my computational domain larger (0,20) x (0,20), and putting the cluster in the center of that, at (10,10). With an interaction range is only 2.5, the periodic images should be decoupled, no? I'm still getting the same inconsistency.

**Comment by gideonsimpson** [comment] 2017-12-04 16:58
Expanding the z box gives much better agreement (correct to 5 significant digits).

**Comment by cortner** [comment] 2017-12-04 18:54
That’s the expected behaviour and what you should do if you don’t want image effects. Or turn off PBC

**Comment by gabor1** [comment] 2017-12-04 19:05
it’s not the behaviour I expect when I turn ON pbc...

-- Gábor

**Comment by cortner** [comment] 2017-12-04 20:45
@gabor1 what do you mean?

**Comment by gabor1** [comment] 2017-12-04 21:50
I'm just saying that if I turn on pbc, I expect it to be honoured, regardless of cutoff. So the minimal image convention is unintuitive to me  

-- Gábor

**Comment by cortner** [comment] 2017-12-04 22:25
ok then we agree anyhow.

@gideonsimpson are you happy to close this or do you want to discuss it some more?

**Comment by gideonsimpson** [comment] 2017-12-04 23:38
Yea, we can close out.

**Closed** 2017-12-04 23:41 UTC
